#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  elevBottom,     sensorTouch)
#pragma config(Sensor, dgtl2,  autoJumper,     sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           frontLeft,     tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port6,           rightLauncher, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftLauncher,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intakeLower,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           intakeUpper,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
CompAutonomous.c
- Basic driver control program for 2014 VEX omni drive base.
- The left joystick Y-axis controls the robot's forward and backward movement.
- The left joystick X-axis controls the robot's left and right movement.
- The right joystick X-axis controls the robot's rotation.
- Button 5 controls the grabber.
- Button 6 controls the elevator.
[I/O Port]          [Name]              [Type]                [Description]
Motor Port 1				
Motor Port 2        frontRight          VEX Motor 393         Front Right motor
Motor Port 3        backRight           VEX Motor 393         Back Right motor
Motor Port 4        frontLeft           VEX Motor 393         Front Left motor
Motor Port 5        backLeft            VEX Motor 393         Back Left motor
Motor Port 6        rightLauncher       VEX Motor 393         Right Launcher primary motor
Motor Port 7        leftLauncher        VEX Motor 393         Left Launcher primary motor
Motor Port 8        intakeLower         VEX Motor 393         Lower intake motor
Motor Port 9				intakeUpper					VEX Motor 393					Upper intake motor
Motor Port 10				
----------------------------------------------------------------------------------------------------*/

// TODO - Add closed-loop control code for drive motor control.

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)    // This is longer than 15 seconds to include external timer padding.
#pragma userControlDuration(120)  // This is longer than 105 seconds to include external timer padding.

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
//#include "AutonomousFunctions.c"

#define ONE_POINT_AUTO true

//Global variables

int frontLeftMotorSpeed = 0;
int frontRightMotorSpeed = 0;
int backRightMotorSpeed = 0;
int backLeftMotorSpeed = 0;
int intakeSpeedUpper = 0;
int intakeSpeedLower = 0;

// All activities that occur before the competition starts
// Example: clearing encoders, setting servo positions, ...
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

}

// Task for the autonomous portion of the competition.
task autonomous()
{

}

// Task for the driver controlled portion of the competition.
task usercontrol()
{
	while (true)
	{

	// Drive commands.
	frontRightMotorSpeed = - vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch1];
	backRightMotorSpeed = - vexRT[Ch3]  - vexRT[Ch4] + vexRT[Ch1];
	frontLeftMotorSpeed =  vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch1];
	backLeftMotorSpeed = vexRT[Ch3] - vexRT[Ch4] + vexRT[Ch1];
	motor[frontRight] = frontRightMotorSpeed;
    	motor[backRight] = backRightMotorSpeed;
    	motor[frontLeft] = frontLeftMotorSpeed;
	motor[backLeft] = backLeftMotorSpeed;

	// Intake control
	intakeSpeedLower = motor[intakeLower];
	intakeSpeedUpper = motor[intakeUpper];
	if (vexRT[Btn6U] == 1) {  // run both intake motors up when button 6 up pressed
	motor[intakeLower] = 127;
	motor[intakeUpper] = 127;    	
	} else if (vexRT[Btn6D] == 1){ // both intake motors up when button 6D pressed
	motor[intakeLower] = -127;
	motor[intakeUpper] = -127;    	
	} 
    
	// Individual intake control
	if (vexRT[Btn5U] == 1) {
	motor[intakeUpper] = 127;  // upper intake runs up
	} else if(vexRT[Btn5D] == 1) {
	motor[intakeLower] = 127;  // lower intake runs up
	} 
	        
	// Launch
	if (vexRT[somebutton] == 1 && launcherSpeed < 127){
    	launcherSpeed++;
    	} else if (launcherSpeed > 0 && vexRT[somebutton] == 0) {
    	launcherSpeed--;
  	}
  	motor[leftLauncher] = launcherSpeed;
	motor[rightLauncher] = launcherSpeed;
	}
}
